esphome:
  name: iec-ce102

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: VERBOSE

external_components:
  - source: github://latonita/esphome-iec61107-meter
    refresh: 10s
    components: [iec61107]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  power_save_mode: NONE

api:
  password: !secret api_password

ota:
  password: !secret ota_password

uart:
    rx_pin: GPIO16
    tx_pin: GPIO17
    baud_rate: 9600
    data_bits: 7
    parity: EVEN
    stop_bits: 1

iec61107:
  id: ce102
  update_interval: 30s
#  receive_timeout: 500ms
#  flow_control_pin: GPIO32

sensor:
  - platform: iec61107
    request: ET0PE(02)
    name: Consumed energy T1
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec61107
    request: ET0PE(03)
    name: Consumed energy T2
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec61107
    name: Current L1
    request: CURRE()
    unit_of_measurement: A
    accuracy_decimals: 2
    device_class: current
    state_class: measurement

  - platform: iec61107
    name: Voltage L1
    request: VOLTA()
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement

  - platform: iec61107
    name: Frequency L1
    request: FREQU()
    unit_of_measurement: Hz
    accuracy_decimals: 2
    device_class: frequency
    state_class: measurement

  - platform: iec61107
    name: Power factor
    request: COS_f()
    unit_of_measurement: "%"
    accuracy_decimals: 2
    device_class: power_factor
    state_class: measurement

  - platform: iec61107
    name: Power
    request: POWEP()
    unit_of_measurement: kW
    accuracy_decimals: 3
    device_class: power
    state_class: measurement
  
text_sensor:
  - platform: iec61107
    name: Serial number
    request: SNUMB()

  - platform: iec61107
    name: Time
    request: TIME_()

  - platform: iec61107
    name: Date
    request: DATE_()

  - platform: iec61107
    name: Info
    request: VINFO()

  - platform: iec61107
    name: Model
    request: MODEL()
