esphome:
  name: neva-mt-iec

# esp8266:
#   board: nodemcuv2

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: VERBOSE

external_components:
  - source: github://latonita/esphome-iec61107-meter
    refresh: 30s
    components: [iec61107]


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  power_save_mode: NONE

api:
  password: !secret api_password

ota:
  platform: esphome
  password: !secret ota_password

status_led:
  pin: GPIO02

button:
  - platform: restart
    id: restart_button
    name: "Restart"

  - platform: safe_mode
    name: "Restart (Safe Mode)"

uart:
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 300
    data_bits: 7
    parity: even
    stop_bits: 1

iec61107:
  - id: meter_01
    update_interval: 30s
    receive_timeout: 3000ms
    baud_rate_handshake: 300
    programming_mode: true  # Счетчики НЕВА требуют формального входа в режим программирования
    password: "00000000"    # и указания пароля (по-умолчанию "00000000")
    crc_method: XOR         # Метод расчета контрольной суммы в Неве - XOR

sensor:
  - platform: iec61107
    obis_code: 0F0880FF     # Ответ от счетчика 0F0880FF(020044.63,015023.90,005020.73,000000.00,000000.00)
    index: 1                # Берем первые скобки
    sub_index: 1            # Первое значение из списка
    name: Energy Total
    unit_of_measurement: kWh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing

  - platform: iec61107
    obis_code: 0F0880FF
    index: 1
    sub_index: 2
    name: Energy T1
    unit_of_measurement: kWh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing

  - platform: iec61107
    obis_code: 0F0880FF
    index: 1
    sub_index: 3
    name: Energy T2
    unit_of_measurement: kWh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing

  # # T3, T4
  # - platform: iec61107
  #   obis_code: 0F0880FF
  #   index: 1
  #   sub_index: 4
  #   name: Energy T3
  #   unit_of_measurement: kWh
  #   accuracy_decimals: 0
  #   device_class: energy
  #   state_class: total_increasing

  # - platform: iec61107
  #   obis_code: 0F0880FF
  #   index: 1
  #   sub_index: 5
  #   name: Energy T4
  #   unit_of_measurement: kWh
  #   accuracy_decimals: 0
  #   device_class: energy
  #   state_class: total_increasing

  # New: Reactive energies. 
  - platform: iec61107
    obis_code: 030880FF
    index: 1
    sub_index: 1
    name: Energy Reactive (+) Total
    unit_of_measurement: kVARh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing

  - platform: iec61107
    obis_code: 030880FF
    index: 1
    sub_index: 2
    name: Energy Reactive (+) T1
    unit_of_measurement: kVARh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing

  - platform: iec61107
    obis_code: 030880FF
    index: 1
    sub_index: 3
    name: Energy Reactive (+) T2
    unit_of_measurement: kVARh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing

  - platform: iec61107
    obis_code: 040880FF
    index: 1
    sub_index: 1
    name: Energy Reactive (-) Total
    unit_of_measurement: kVARh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing

  - platform: iec61107
    obis_code: 040880FF
    index: 1
    sub_index: 2
    name: Energy Reactive (-) T1
    unit_of_measurement: kVARh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing

  - platform: iec61107
    obis_code: 040880FF
    index: 1
    sub_index: 3
    name: Energy Reactive (-) T2
    unit_of_measurement: kVARh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing

  # Already present: Active Power total
  - platform: iec61107
    name: Active Power
    obis_code: 100700FF
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement

  # New: Per-phase active power
  - platform: iec61107
    name: Active Power L1
    obis_code: 240700FF
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement

  - platform: iec61107
    name: Active Power L2
    obis_code: 380700FF
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement

  - platform: iec61107
    name: Active Power L3
    obis_code: 4C0700FF
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement

  # Already present: Urms A/B/C
  - platform: iec61107
    name: Voltage L1
    obis_code: 200700FF
    unit_of_measurement: V
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement

  - platform: iec61107
    name: Voltage L2
    obis_code: 340700FF
    unit_of_measurement: V
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement

  - platform: iec61107
    name: Voltage L3
    obis_code: 480700FF
    unit_of_measurement: V
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement

  # Already present: Irms A/B/C
  - platform: iec61107
    name: Current L1
    obis_code: 1F0700FF
    index: 1
    unit_of_measurement: A
    accuracy_decimals: 3
    device_class: current
    state_class: measurement

  - platform: iec61107
    name: Current L2
    obis_code: 330700FF
    unit_of_measurement: A
    accuracy_decimals: 3
    device_class: current
    state_class: measurement

  - platform: iec61107
    name: Current L3
    obis_code: 470700FF
    unit_of_measurement: A
    accuracy_decimals: 3
    device_class: current
    state_class: measurement

  # Already present
  - platform: iec61107
    name: Frequency
    obis_code: 0E0701FF
    unit_of_measurement: Hz
    accuracy_decimals: 1
    device_class: frequency
    state_class: measurement

  # New: Voltage angles
  - platform: iec61107
    name: Voltage angle L1-L2
    obis_code: 51070AFF
    unit_of_measurement: °
    accuracy_decimals: 1
    state_class: measurement

  - platform: iec61107
    name: Voltage angle L3-L1
    obis_code: 510714FF
    unit_of_measurement: °
    accuracy_decimals: 1
    state_class: measurement

  - platform: iec61107
    name: Voltage angle L2-L3
    obis_code: 510715FF
    unit_of_measurement: °
    accuracy_decimals: 1
    state_class: measurement

  # New: Power factors
  - platform: iec61107
    name: Power Factor L1
    obis_code: 2107FFFF
    unit_of_measurement: ""
    accuracy_decimals: 3
    state_class: measurement

  - platform: iec61107
    name: Power Factor L2
    obis_code: 3507FFFF
    unit_of_measurement: ""
    accuracy_decimals: 3
    state_class: measurement

  - platform: iec61107
    name: Power Factor L3
    obis_code: 4907FFFF
    unit_of_measurement: ""
    accuracy_decimals: 3
    state_class: measurement

  - platform: iec61107
    name: Power Factor Total
    obis_code: 0D07FFFF
    unit_of_measurement: ""
    accuracy_decimals: 3
    state_class: measurement

  # Already present
  - platform: iec61107
    name: Temperature
    obis_code: 600900FF
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address

  - platform: iec61107
    name: Serial number
    obis_code: 600100FF
    entity_category: diagnostic

  - platform: iec61107
    name: Time
    obis_code: 000901FF
    entity_category: diagnostic
    filters:
      - lambda: |-
          std::string str = x.substr(0,2) + ":" + x.substr(2,2) + ":" + x.substr(4,2);
          return str;

  - platform: iec61107
    name: Date
    obis_code: 000902FF
    entity_category: diagnostic
    filters:
      - lambda: |-
          std::string str = "20" + x.substr(0,2) + "-" + x.substr(2,2) + "-" + x.substr(4,2);
          return str;
